DOMAIN = "ptlevel"
CONF_CONNECTION_TYPE = "connection_type"
CONF_IP_ADDRESS = "ip_address"
CONF_API_TOKEN = "api_token"
CONF_DEVICE_ID = "device_id"
CONF_TANK_SIZE = "tank_size"
CONF_FULL_AD = "full_ad"

CONNECTION_LOCAL = "local"
CONNECTION_TOKEN = "token"
